# Generated by Django 2.2.7 on 2021-02-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=500)),
                ('following_time', models.DateTimeField()),
                ('following_type', models.IntegerField(choices=[(1, '门诊随访'), (2, '慢性病随访'), (3, '出院随访'), (4, '其他')], default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_doctor', to='profiles.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_patient', to='profiles.Patient')),
            ],
        ),
    ]
