# Generated by Django 2.2.7 on 2021-02-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=500)),
                ('filed_time', models.DateTimeField(default=None, null=True)),
                ('closed_time', models.DateTimeField(default=None, null=True)),
                ('d_type', models.IntegerField(choices=[(1, '优先门诊法'), (2, '先到先看病'), (3, '间隔一定数量'), (4, '无')], default=1)),
                ('appointment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_appointment', to='appointments.Appointment')),
            ],
        ),
    ]
